kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - &host grafana.home.ismailbay.at
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    envFromSecret: grafana-secrets
    grafana.ini:
      server:
        root_url: https://grafana.home.ismailbay.at
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false