---

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: prereq
      become: true

- hosts: master
  roles:
    - role: master
      become: true

- hosts: node
  roles:
    - role: node
      become: true

- hosts: master
  roles:
    - role: post
      become: true
