argo-cd:
  server:
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics